![SPU Logo](https://logos-download.com/wp-content/uploads/2019/07/Saint_Peters_University_Logo.png)

<table style="border-collapse: collapse; width: 100%; table-layout: fixed;">
  <tr>
    <th style="background-color: #ADD8E6; padding: 12px; text-align: left; font-size: 20px; width: 30%;">Student First Name</th>
    <td style="padding: 12px; font-size: 20px; width: 70%;"><b>Kristopher</b></td>
  </tr>
  <tr>
    <th style="background-color: #ADD8E6; padding: 12px; text-align: left; font-size: 20px; width: 30%;">Student Last Name</th>
    <td style="padding: 12px; font-size: 20px; width: 70%;"><b>Albano</b></td>
  </tr>
  <tr>
    <th style="background-color: #ADD8E6; padding: 12px; text-align: left; font-size: 20px; width: 30%;">Demo #</th>
    <td style="padding: 12px; font-size: 20px; width: 70%;">Capstone Project</td>
  </tr>
  <tr>
    <th style="background-color: #ADD8E6; padding: 12px; text-align: left; font-size: 20px; width: 30%;">Subject</th>
    <td style="padding: 12px; font-size: 20px; width: 70%;">AI-Driven Fundraising Models</td>
  </tr>
</table>

# AI-Driven_Fundraising_Models
Fundraising in higher education institutions has evolved in recent years where a large part was played by the increasing adoption of online donation platforms. This online shift, accelerated by the COVID-19 pandemic, has reshaped how colleges and universities connect with donors to secure funding to meet financial demands that the institution alone cannot cover. Fundraising efforts play an integral part in supporting everything from student financial aid and facility upgrades to operational expenses making it essential for institutions to adapt to the changing expectations of their donor base.

## Business Needs
The success of fundraising campaigns in higher education institutions relies a lot on understanding and adapting to donor behaviors. Generational shifts in giving habits in recent years have presented a lot of different challenges in maintaining consistent campaigns that can effectively reach different demographic groups. Fortunately, several technological advancements offer new opportunities to easily identify trends and allow for a more seamless donation process. It is important to understand how higher education institutions can leverage this transition not only to help the students and staff, but also the community surrounding them. This project will aim to analyze these trends to better understand how to improve fundraising efforts to enable the university to better communicate the needs of the institution to donors across different age groups. By doing so, institutions can optimize their fundraising strategies to ensure financial sustainability and fulfill their educational missions in an ever-changing philanthropic landscape.

## Problem Statement
This study seeks to address this gap by examining the impact of technological advancements on fundraising practices, focusing on the transition to online donation platforms and its implications for donor engagement and fundraising efficiency in higher education.

## Minimum Viable Product 
1. Donor Behavior Overview
Percentage of online vs offline donors
Average donation amount (online vs offline)
Age distribution of online donors
2. Donation Trends
Comparison of online donation growth to overall donation growth
3. Recent Campaign Performance
Analysis of the results from the recently closed campaign
Online vs offline gifts comparison


## High Level Architecture
![Alt text](../Media/HLA.png)

## Credit: Kristopher

# Exploratory Data Analysis

### Data Acquisition

In [1]:
## Required Libraries 
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_excel('../Dataset/fundraising_online_dataset.XLS')

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [3]:
df.head()

,Key Indicator,Constituent ID,Age,Preferred State,Gift Date,Gift Amount,Fund Split Amount,Fund Description,Campaign Description,Total Amount of Gifts_1,Gift Total Number of Gifts_1,Gift Payment Type,Gift Batch Description,First Gift Date,First Gift Amount,Last Gift Date,Last Gift Amount
0,Individual,8944,60.0,New Jersey,2023-04-25,450.0,160.0,305-Hearts & Minds Scholarship Dinner (DAA),New Campaign,4045.0,9,Venmo,NetCommunity Event Registration Fees,1989-06-30,100.0,2024-08-12,50.0
1,Individual,408153,55.0,NaN,2023-05-05,35.0,35.0,331-Unrestricted,New Campaign,35.0,1,Venmo,NetCommunity Event Registration Fees,2023-05-05,35.0,2023-05-05,35.0
2,Individual,408242,NaN,New Jersey,2023-05-31,50.0,50.0,331-Unrestricted,New Campaign,50.0,1,Venmo,NetCommunity Donations,2023-05-31,50.0,2023-05-31,50.0
3,Individual,407834,NaN,NaN,2023-05-03,35.0,35.0,331-Unrestricted,New Campaign,35.0,1,Venmo,NetCommunity Event Registration Fees,2023-05-03,35.0,2023-05-03,35.0
4,Individual,39161,50.0,Florida,2023-04-28,100.0,100.0,331-Unrestricted,New Campaign,223.0,2,Venmo,NetCommunity Event Registration Fees,1996-03-12,25.0,2023-05-18,123.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13503 entries, 0 to 13502
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Key Indicator                 13503 non-null  object
 1   Constituent ID                13503 non-null  object
 2   Age                           8559 non-null   float64
 3   Preferred State               13161 non-null  object
 4   Gift Date                     13503 non-null  datetime64[ns]
 5   Gift Amount                   13503 non-null  float64
 6   Fund Split Amount             13503 non-null  float64
 7   Fund Description              13503 non-null  object
 8   Campaign Description          13503 non-null  object
 9   Total Amount of Gifts_1       13503 non-null  float64
 10  Gift Total Number of Gifts_1  13503 non-null  int64
 11  Gift Payment Type             13503 non-null  object
 12  Gift Batch Description        10987 non-null  object
 13  First Gift Date               13503 non-null  datetime64[ns]
 14  First Gift Amount             13503 non-null  float64
 15  Last Gift Date                13503 non-null  datetime64[ns]
 16  Last Gift Amount              13503 non-null  float64
dtypes: datetime64[ns](3), float64(6), int64(1), object(7)
memory usage: 1.8+ MB

In [5]:
df.describe()

,Age,Gift Date,Gift Amount,Fund Split Amount,Total Amount of Gifts_1,Gift Total Number of Gifts_1,First Gift Date,First Gift Amount,Last Gift Date,Last Gift Amount
count,8559.000000,13503,13503.000000,13503.000000,13503.000000,13503.000000,13503,13503.000000,13503,13503.000000
mean,63.020213,2021-11-24 20:51:33.712508416,340.279307,277.101264,3289.228165,11.908465,1996-03-05 12:47:17.769384704,227.828269,2023-08-02 09:04:50.335480832,736.094818
min,0.000000,2018-06-18 00:00:00,0.000000,0.000000,0.000000,0.000000,1960-01-01 00:00:00,0.000000,2018-06-18 00:00:00,0.000000
25%,51.000000,2020-08-30 12:00:00,50.000000,40.000000,165.450000,2.000000,1976-06-30 00:00:00,20.000000,2022-11-29 00:00:00,50.000000
50%,67.000000,2022-03-16 00:00:00,100.000000,100.000000,684.550000,5.000000,1995-12-05 00:00:00,35.000000,2024-02-03 00:00:00,100.000000
75%,75.000000,2023-04-05 00:00:00,250.000000,200.000000,3029.680000,12.000000,2017-12-06 00:00:00,100.000000,2024-09-07 00:00:00,250.000000
max,152.000000,2024-06-30 00:00:00,50000.000000,50000.000000,150000.000000,131.000000,2024-06-20 00:00:00,101950.000000,2024-12-02 00:00:00,169856.000000
std,16.581692,NaN,1184.933519,1000.499270,7763.622936,20.164728,NaN,2191.152685,NaN,5310.788472

In [7]:
print("✅ The number of rows in my dataset is", df.shape[0])
print("✅ The number of columns in my dataset is", df.shape[1])

✅ The number of rows in my dataset is 13503
✅ The number of columns in my dataset is 17

In [8]:
df.columns

Index(['Key Indicator', 'Constituent ID', 'Age', 'Preferred State',
       'Gift Date', 'Gift Amount', 'Fund Split Amount', 'Fund Description',
       'Campaign Description', 'Total Amount of Gifts_1',
       'Gift Total Number of Gifts_1', 'Gift Payment Type',
       'Gift Batch Description', 'First Gift Date', 'First Gift Amount',
       'Last Gift Date', 'Last Gift Amount'],
      dtype='object')